version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-database'
    environment:
      - 'POSTGRES_USER={username in DB)'
      - 'POSTGRES_PASSWORD={password in DB}'
      - 'POSTGRES_DB={name table in DB}'

  admin:
    build: ./AdminServer
    container_name: 'admin-server'
    ports:
      - "9090:9090"

  server:
    build: ./ResourceServer
    container_name: 'resource-server'
    ports:
      - "8080:8080"

  telegrambot:
    build: ./TelegramBot
    container_name: 'telegram-bot'
    ports:
      - "8000:8000"

