spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: <url to DB>
    username: <username to DB>
    password: <password to DB>
  jpa:
    hibernate:
      ddl-auto: update
